language: c
build:
  cache: true
  cache_dir_list:
    - /root/.ccache
  pre_ci_boot:
    image_name: jforissier/optee_os_ci_clangbuilt
    image_tag: latest
    pull: true
    options: "-e HOME=/root"
  ci:
    - export LC_ALL=C
    - export PATH=/usr/local/bin:$PATH  # clang
    - export CROSS_COMPILE32="ccache arm-linux-gnueabihf-"
    - export CROSS_COMPILE64="ccache aarch64-linux-gnu-"
    - export CFG_DEBUG_INFO=n
    - export CFG_WERROR=y
    - function _make() { make -j$(getconf _NPROCESSORS_ONLN) -s O=out $* && ccache -s && ccache -z; }
    - ccache -z

    - _make
    - _make COMPILER=clang
    - _make PLATFORM=vexpress-qemu_armv8a CFG_ARM64_core=y COMPILER=clang
    - _make PLATFORM=hikey-hikey960 COMPILER=clang
    - _make PLATFORM=hikey-hikey960 CFG_ARM64_core=y COMPILER=clang
